# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VHDL/Digital-Design-with-HDL/clk_div/clk_div.cache/wt [current_project]
set_property parent.project_path D:/VHDL/Digital-Design-with-HDL/clk_div/clk_div.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib D:/VHDL/Digital-Design-with-HDL/clk_div/clk_div.srcs/sources_1/new/cld_div.vhd
synth_design -top cld_div -part xc7a100tcsg324-1
write_checkpoint -noxdef cld_div.dcp
catch { report_utilization -file cld_div_utilization_synth.rpt -pb cld_div_utilization_synth.pb }
