# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.cache/wt [current_project]
set_property parent.project_path D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.srcs/sources_1/new/shift_right.vhd
  D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.srcs/sources_1/new/clock_divider.vhd
  D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.srcs/sources_1/new/main.vhd
}
read_xdc D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.srcs/constrs_1/imports/new/Ready.xdc
set_property used_in_implementation false [get_files D:/VHDL/Digital-Design-with-HDL/tutoMarch_11_16_26/tutoMarch_11_16_26.srcs/constrs_1/imports/new/Ready.xdc]

synth_design -top main -part xc7a100tcsg324-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
